# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_name=Copperworks
mod_id=copperworks
mod_version=3.0.6
mod_authors=uhmbyee / Mariany Pinkston
mod_description=Expand uses for copper with new redstone components and items.
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/copperworks
mod_git_url=https://github.com/marianyp/copperworks
mod_license=ARR

maven_group=dev.mariany.copperworks
archives_base_name=copperworks

# Dependencies
fabric_version=0.141.2+1.21.11